# Generated by Django 2.1.5 on 2019-01-14 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('cod_aluguel', models.IntegerField(primary_key=True, serialize=False)),
                ('data_festa', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('valor_cobrado', models.FloatField()),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Alugueis',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40, verbose_name='Cliente:')),
                ('telefone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('cod_endere', models.IntegerField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=40)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
            },
        ),
        migrations.CreateModel(
            name='ItemTema',
            fields=[
                ('cod_item', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'ItemTema',
                'verbose_name_plural': 'ItensTemas',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('cod_tema', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('valor_aluguel', models.FloatField()),
                ('cor_toalha', models.CharField(max_length=20)),
                ('cod_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ItemTema')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.AddField(
            model_name='aluguel',
            name='cod_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='cod_endere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Endereco'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='cod_tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tema'),
        ),
    ]
